### ISSUE TITLE
localtunnel not forwarding dockerized app 

### ISSUE THREAD

**Issue by Blerr511** [localtunnel/localtunnel#424]
Hi , i'm trying to run localtunnel in my docker container, i have this code in my **docker-compose.yml** file
`  localtunnel:
    container_name: my_tunnel
    image: api_server
    depends_on:
      - postgres
      - server
      - redis
    entrypoint: npm run localtunnel
`
and `    "localtunnel": "lt --port 5000 --subdomain myhost"` script in my package.json
i see output of command , and it's returning host of my localtunnel ,  but i got 504 gateway error when i tried to open that uri.
P.S. output of my **docker ps** command
`4b92695dbb4d   api_server           "npm run localtunnel"    35 seconds ago   Up 33 seconds                 3000/tcp                                                                                         my_tunnel`

**Comment by joe-niland** [comment]
localtunnel needs to run in `host` networking mode (I think) so you need to expose your `server` container port on the host and then forward it.

Here's a docker-compose sample:

```
localtunnel:
    build:
      context: ./
      dockerfile: ./env/docker/localtunnel/Dockerfile
    restart: on-failure
    network_mode: host
    depends_on:
      - server
    environment:
      PORT: 21080
```

localtunnel/Dockerfile:

```
FROM node:slim

ENV PORT=80
ENV LOCAL_HOST=localhost

RUN npm install -g localtunnel
# lt process uses above env vars
ENTRYPOINT ["usr/local/bin/lt"]
```
