### ISSUE TITLE
endpoint IP is not correct

### ISSUE THREAD

**Issue by AmirRezaM75** [localtunnel/localtunnel#609]
when opening generated url, it asks me to enter the public address, also it suggest to visit https://ipv4.icanhazip.com/ website to get your ip address but after entering mine i get following error:
**Error: endpoint IP is not correct. Please try again or contact whoever gave you this link for the correct public IP.**

**Comment by angelpinheiro** [comment]
This also occurs to me, but only while deploying localtunnel with docker-compose. Here it is my `docker-compose.yml`:
```
services:     
server:        
  build: .
  ports:
    - "8080:8080"        
localtunnel:
  image: efrecon/localtunnel
  links:
    - server
  command:
    --local-host server --port 8080 --subdomain customsubdomain
```


PD: I would suggest renaming this issue to "Public IP confirmation fails" or something similar in order to make it more descriptive.
